Update generate-x86_64.yml

diff --git a/.github/workflows/generate-x86_64.yml b/.github/workflows/generate-x86_64.yml
--- a/.github/workflows/generate-x86_64.yml
+++ b/.github/workflows/generate-x86_64.yml
@@ -56,7 +56,10 @@ jobs:
       - name: Download External Packages
         working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-x86-64.Linux-x86_64
         run: |
-          cat external-package-urls.txt | xargs wget -P packages
+          cat external-package-urls.txt | while read url; do
+            echo "Downloading: $url"
+            wget -P packages "$url" || echo "ERROR: Failed to download $url"
+          done        
       
       - name: Run Patch and DIY Scripts
         working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-x86-64.Linux-x86_64
